version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
    groups:
      riverqueue:
        patterns:
          - "github.com/riverqueue/river*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      sentry:
        patterns:
          - "github.com/getsentry/sentry-go*"
    cooldown:
      default-days: 14
